FROM alpine:latest AS base


RUN apk add --no-cache build-base linux-headers ncurses-dev

WORKDIR /src

ARG BUSYBOX_VERSION
RUN wget https://busybox.net/downloads/busybox-${BUSYBOX_VERSION}.tar.bz2

RUN tar -xvf busybox-${BUSYBOX_VERSION}.tar.bz2

WORKDIR /src/busybox-${BUSYBOX_VERSION}

